package:
  name: cargo
  version: v0.1.0
  authors:
    - author: 
      email: 
      organization: 
  dependencies:
    chaos:
      repository: github.com/chaos-io/chaos
      version: v0.0.0-20250722065453-4794df450c1d
    chaos.core:
      repository: github.com/chaos-io/core/go
      version: v0.0.0-20251006124144-74c83954cdc8
  repository: github.com/chaos-io/cargo
