// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date: 2025-10-08T20:15:43.419+08:00

package middleware

import (
	"github.com/chaos-io/gokit/tracing"
	"go.opentelemetry.io/otel/trace"

	// this service api
	"github.com/chaos-io/cargo/backend/modules/cargo-server/api/endpoint"
)

func wrapTracer(in endpoint.Endpoints, options map[string]any) {
	var tracer trace.Tracer
	if value, ok := options["tracer"]; ok && value != nil {
		tracer = value.(trace.Tracer)
	} else {
		return
	}

	in.GetCargoEndpoint = tracing.TraceServer(tracer, "GetCargo")(in.GetCargoEndpoint)
	in.CreateCargoEndpoint = tracing.TraceServer(tracer, "CreateCargo")(in.CreateCargoEndpoint)
	in.HandingEventEndpoint = tracing.TraceServer(tracer, "HandingEvent")(in.HandingEventEndpoint)
}
