// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package middleware

import (
	"github.com/chaos-io/gokit/middleware"

	// this service api
	"github.com/chaos-io/cargo/backend/modules/cargo-server/api/endpoint"
)

func wrapValidator(in endpoint.Endpoints, options map[string]any) {
	if value, ok := options["validator"]; !ok || value == nil {
		return
	}

	in.GetCargoEndpoint = middleware.ValidatorMW()(in.GetCargoEndpoint)
	in.CreateCargoEndpoint = middleware.ValidatorMW()(in.CreateCargoEndpoint)
	in.HandingEventEndpoint = middleware.ValidatorMW()(in.HandingEventEndpoint)
}
