// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date: 2025-10-08T20:15:43.419+08:00

package middleware

import (
	"github.com/chaos-io/gokit/middleware/validator"

	// this service api
	"github.com/chaos-io/cargo/backend/modules/cargo-server/api/endpoint"
)

func wrapValidator(in endpoint.Endpoints, options map[string]any) {
	if value, ok := options["validator"]; !ok || value == nil {
		return
	}

	in.GetCargoEndpoint = validator.ValidatorMW()(in.GetCargoEndpoint)
	in.CreateCargoEndpoint = validator.ValidatorMW()(in.CreateCargoEndpoint)
	in.HandingEventEndpoint = validator.ValidatorMW()(in.HandingEventEndpoint)
}
