// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: cargo/cargo.proto

package cargo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cargo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string                 `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Shipper    *Customer              `protobuf:"bytes,5,opt,name=Shipper,proto3" json:"Shipper,omitempty"`
	Consignee  *Customer              `protobuf:"bytes,6,opt,name=Consignee,proto3" json:"Consignee,omitempty"`
	Spec       *DeliverySpecification `protobuf:"bytes,10,opt,name=Spec,proto3" json:"Spec,omitempty"`
}

func (x *Cargo) Reset() {
	*x = Cargo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cargo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cargo) ProtoMessage() {}

func (x *Cargo) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cargo.ProtoReflect.Descriptor instead.
func (*Cargo) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{0}
}

func (x *Cargo) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *Cargo) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Cargo) GetShipper() *Customer {
	if x != nil {
		return x.Shipper
	}
	return nil
}

func (x *Cargo) GetConsignee() *Customer {
	if x != nil {
		return x.Consignee
	}
	return nil
}

func (x *Cargo) GetSpec() *DeliverySpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Customer) Reset() {
	*x = Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeliverySpecification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From *Location              `protobuf:"bytes,5,opt,name=From,proto3" json:"From,omitempty"`
	To   *Location              `protobuf:"bytes,6,opt,name=To,proto3" json:"To,omitempty"`
	ETA  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=ETA,proto3" json:"ETA,omitempty"`
}

func (x *DeliverySpecification) Reset() {
	*x = DeliverySpecification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverySpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverySpecification) ProtoMessage() {}

func (x *DeliverySpecification) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverySpecification.ProtoReflect.Descriptor instead.
func (*DeliverySpecification) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverySpecification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliverySpecification) GetFrom() *Location {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DeliverySpecification) GetTo() *Location {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DeliverySpecification) GetETA() *timestamppb.Timestamp {
	if x != nil {
		return x.ETA
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port string `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type CarrierMovement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleId string    `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	From       *Location `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To         *Location `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *CarrierMovement) Reset() {
	*x = CarrierMovement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarrierMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierMovement) ProtoMessage() {}

func (x *CarrierMovement) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierMovement.ProtoReflect.Descriptor instead.
func (*CarrierMovement) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{4}
}

func (x *CarrierMovement) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CarrierMovement) GetFrom() *Location {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CarrierMovement) GetTo() *Location {
	if x != nil {
		return x.To
	}
	return nil
}

type DeliveryHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CargoId      string                 `protobuf:"bytes,3,opt,name=cargo_id,json=cargoId,proto3" json:"cargo_id,omitempty"`
	ScheduleId   string                 `protobuf:"bytes,4,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	CompleteTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CompleteTime,proto3" json:"CompleteTime,omitempty"`
}

func (x *DeliveryHistory) Reset() {
	*x = DeliveryHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryHistory) ProtoMessage() {}

func (x *DeliveryHistory) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryHistory.ProtoReflect.Descriptor instead.
func (*DeliveryHistory) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryHistory) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeliveryHistory) GetCargoId() string {
	if x != nil {
		return x.CargoId
	}
	return ""
}

func (x *DeliveryHistory) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *DeliveryHistory) GetCompleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompleteTime
	}
	return nil
}

type HandlingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cargo        *Cargo                 `protobuf:"bytes,1,opt,name=cargo,proto3" json:"cargo,omitempty"`
	EventType    string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	CompleteTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CompleteTime,proto3" json:"CompleteTime,omitempty"`
	Movement     *CarrierMovement       `protobuf:"bytes,10,opt,name=movement,proto3" json:"movement,omitempty"`
}

func (x *HandlingEvent) Reset() {
	*x = HandlingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_cargo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlingEvent) ProtoMessage() {}

func (x *HandlingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_cargo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlingEvent.ProtoReflect.Descriptor instead.
func (*HandlingEvent) Descriptor() ([]byte, []int) {
	return file_cargo_cargo_proto_rawDescGZIP(), []int{6}
}

func (x *HandlingEvent) GetCargo() *Cargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

func (x *HandlingEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HandlingEvent) GetCompleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompleteTime
	}
	return nil
}

func (x *HandlingEvent) GetMovement() *CarrierMovement {
	if x != nil {
		return x.Movement
	}
	return nil
}

var File_cargo_cargo_proto protoreflect.FileDescriptor

var file_cargo_cargo_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x05,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f,
	0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x07, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x65, 0x72, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x65, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x53,
	0x70, 0x65, 0x63, 0x22, 0x2e, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a,
	0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61,
	0x72, 0x67, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x46, 0x72,
	0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x02, 0x54, 0x6f, 0x12, 0x2c, 0x0a, 0x03, 0x45, 0x54, 0x41, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x45, 0x54,
	0x41, 0x22, 0x32, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x78, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72,
	0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1f,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x72,
	0x67, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x6f, 0x22,
	0xb1, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x67, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x67, 0x6f,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72,
	0x67, 0x6f, 0x52, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x72,
	0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x7b, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x42, 0x0a, 0x43, 0x61, 0x72, 0x67, 0x6f,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6f, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x61, 0x72,
	0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x67,
	0x6f, 0x3b, 0x63, 0x61, 0x72, 0x67, 0x6f, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x05,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0xca, 0x02, 0x05, 0x43, 0x61, 0x72, 0x67, 0x6f, 0xe2, 0x02, 0x11,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x05, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cargo_cargo_proto_rawDescOnce sync.Once
	file_cargo_cargo_proto_rawDescData = file_cargo_cargo_proto_rawDesc
)

func file_cargo_cargo_proto_rawDescGZIP() []byte {
	file_cargo_cargo_proto_rawDescOnce.Do(func() {
		file_cargo_cargo_proto_rawDescData = protoimpl.X.CompressGZIP(file_cargo_cargo_proto_rawDescData)
	})
	return file_cargo_cargo_proto_rawDescData
}

var file_cargo_cargo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cargo_cargo_proto_goTypes = []interface{}{
	(*Cargo)(nil),                 // 0: cargo.Cargo
	(*Customer)(nil),              // 1: cargo.Customer
	(*DeliverySpecification)(nil), // 2: cargo.DeliverySpecification
	(*Location)(nil),              // 3: cargo.Location
	(*CarrierMovement)(nil),       // 4: cargo.CarrierMovement
	(*DeliveryHistory)(nil),       // 5: cargo.DeliveryHistory
	(*HandlingEvent)(nil),         // 6: cargo.HandlingEvent
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_cargo_cargo_proto_depIdxs = []int32{
	1,  // 0: cargo.Cargo.Shipper:type_name -> cargo.Customer
	1,  // 1: cargo.Cargo.Consignee:type_name -> cargo.Customer
	2,  // 2: cargo.Cargo.Spec:type_name -> cargo.DeliverySpecification
	3,  // 3: cargo.DeliverySpecification.From:type_name -> cargo.Location
	3,  // 4: cargo.DeliverySpecification.To:type_name -> cargo.Location
	7,  // 5: cargo.DeliverySpecification.ETA:type_name -> google.protobuf.Timestamp
	3,  // 6: cargo.CarrierMovement.from:type_name -> cargo.Location
	3,  // 7: cargo.CarrierMovement.to:type_name -> cargo.Location
	7,  // 8: cargo.DeliveryHistory.CompleteTime:type_name -> google.protobuf.Timestamp
	0,  // 9: cargo.HandlingEvent.cargo:type_name -> cargo.Cargo
	7,  // 10: cargo.HandlingEvent.CompleteTime:type_name -> google.protobuf.Timestamp
	4,  // 11: cargo.HandlingEvent.movement:type_name -> cargo.CarrierMovement
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cargo_cargo_proto_init() }
func file_cargo_cargo_proto_init() {
	if File_cargo_cargo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cargo_cargo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cargo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_cargo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_cargo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverySpecification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_cargo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_cargo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarrierMovement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_cargo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_cargo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cargo_cargo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cargo_cargo_proto_goTypes,
		DependencyIndexes: file_cargo_cargo_proto_depIdxs,
		MessageInfos:      file_cargo_cargo_proto_msgTypes,
	}.Build()
	File_cargo_cargo_proto = out.File
	file_cargo_cargo_proto_rawDesc = nil
	file_cargo_cargo_proto_goTypes = nil
	file_cargo_cargo_proto_depIdxs = nil
}
