// TODO: svc/endpoints.go
// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package endpoint

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	// this service api
	"github.com/chaos-io/cargo/genproto/cargo"
	pb "github.com/chaos-io/cargo/genproto/cargo/v1"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	CreateResourceEndpoint endpoint.Endpoint
	GetResourceEndpoint    endpoint.Endpoint
	ListResourcesEndpoint  endpoint.Endpoint
	UpdateResourceEndpoint endpoint.Endpoint
	DeleteResourceEndpoint endpoint.Endpoint
}

// Endpoints

func (e Endpoints) CreateResource(ctx context.Context, in *pb.CreateResourceRequest) (*cargo.Resource, error) {
	response, err := e.CreateResourceEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*cargo.Resource), nil
}

func (e Endpoints) GetResource(ctx context.Context, in *pb.GetResourceRequest) (*cargo.Resource, error) {
	response, err := e.GetResourceEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*cargo.Resource), nil
}

func (e Endpoints) ListResources(ctx context.Context, in *pb.ListResourcesRequest) (*pb.ListResourcesResponse, error) {
	response, err := e.ListResourcesEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ListResourcesResponse), nil
}

func (e Endpoints) UpdateResource(ctx context.Context, in *pb.UpdateResourceRequest) (*cargo.Resource, error) {
	response, err := e.UpdateResourceEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*cargo.Resource), nil
}

func (e Endpoints) DeleteResource(ctx context.Context, in *pb.DeleteResourceRequest) (*pb.DeleteResourceResponse, error) {
	response, err := e.DeleteResourceEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.DeleteResourceResponse), nil
}

// Make Endpoints

func MakeCreateResourceEndpoint(s pb.CargoServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.CreateResourceRequest)
		v, err := s.CreateResource(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetResourceEndpoint(s pb.CargoServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetResourceRequest)
		v, err := s.GetResource(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeListResourcesEndpoint(s pb.CargoServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ListResourcesRequest)
		v, err := s.ListResources(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeUpdateResourceEndpoint(s pb.CargoServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.UpdateResourceRequest)
		v, err := s.UpdateResource(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeDeleteResourceEndpoint(s pb.CargoServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.DeleteResourceRequest)
		v, err := s.DeleteResource(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"CreateResource": struct{}{},
		"GetResource":    struct{}{},
		"ListResources":  struct{}{},
		"UpdateResource": struct{}{},
		"DeleteResource": struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "CreateResource" {
			e.CreateResourceEndpoint = middleware(e.CreateResourceEndpoint)
		}
		if inc == "GetResource" {
			e.GetResourceEndpoint = middleware(e.GetResourceEndpoint)
		}
		if inc == "ListResources" {
			e.ListResourcesEndpoint = middleware(e.ListResourcesEndpoint)
		}
		if inc == "UpdateResource" {
			e.UpdateResourceEndpoint = middleware(e.UpdateResourceEndpoint)
		}
		if inc == "DeleteResource" {
			e.DeleteResourceEndpoint = middleware(e.DeleteResourceEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"CreateResource": struct{}{},
		"GetResource":    struct{}{},
		"ListResources":  struct{}{},
		"UpdateResource": struct{}{},
		"DeleteResource": struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "CreateResource" {
			e.CreateResourceEndpoint = middleware("CreateResource", e.CreateResourceEndpoint)
		}
		if inc == "GetResource" {
			e.GetResourceEndpoint = middleware("GetResource", e.GetResourceEndpoint)
		}
		if inc == "ListResources" {
			e.ListResourcesEndpoint = middleware("ListResources", e.ListResourcesEndpoint)
		}
		if inc == "UpdateResource" {
			e.UpdateResourceEndpoint = middleware("UpdateResource", e.UpdateResourceEndpoint)
		}
		if inc == "DeleteResource" {
			e.DeleteResourceEndpoint = middleware("DeleteResource", e.DeleteResourceEndpoint)
		}
	}
}
