// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: cargo/v1/cargo.proto

package cargo

import (
	cargo "github.com/chaos-io/cargo/genproto/cargo"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCargoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *GetCargoReq) Reset() {
	*x = GetCargoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_v1_cargo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCargoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoReq) ProtoMessage() {}

func (x *GetCargoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoReq.ProtoReflect.Descriptor instead.
func (*GetCargoReq) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{0}
}

func (x *GetCargoReq) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *GetCargoReq) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetCargoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cargo *cargo.Cargo `protobuf:"bytes,1,opt,name=cargo,proto3" json:"cargo,omitempty"`
}

func (x *GetCargoResp) Reset() {
	*x = GetCargoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_v1_cargo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCargoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoResp) ProtoMessage() {}

func (x *GetCargoResp) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoResp.ProtoReflect.Descriptor instead.
func (*GetCargoResp) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{1}
}

func (x *GetCargoResp) GetCargo() *cargo.Cargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

type CreateCargoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cargo *cargo.Cargo `protobuf:"bytes,1,opt,name=cargo,proto3" json:"cargo,omitempty"`
}

func (x *CreateCargoReq) Reset() {
	*x = CreateCargoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_v1_cargo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCargoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCargoReq) ProtoMessage() {}

func (x *CreateCargoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCargoReq.ProtoReflect.Descriptor instead.
func (*CreateCargoReq) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCargoReq) GetCargo() *cargo.Cargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

type CreateCargoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
}

func (x *CreateCargoResp) Reset() {
	*x = CreateCargoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_v1_cargo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCargoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCargoResp) ProtoMessage() {}

func (x *CreateCargoResp) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCargoResp.ProtoReflect.Descriptor instead.
func (*CreateCargoResp) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCargoResp) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type HandingEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *cargo.HandlingEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *HandingEventReq) Reset() {
	*x = HandingEventReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_v1_cargo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandingEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandingEventReq) ProtoMessage() {}

func (x *HandingEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandingEventReq.ProtoReflect.Descriptor instead.
func (*HandingEventReq) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{4}
}

func (x *HandingEventReq) GetEvent() *cargo.HandlingEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type HandingEventResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HandingEventResp) Reset() {
	*x = HandingEventResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargo_v1_cargo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandingEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandingEventResp) ProtoMessage() {}

func (x *HandingEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandingEventResp.ProtoReflect.Descriptor instead.
func (*HandingEventResp) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{5}
}

func (x *HandingEventResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_cargo_v1_cargo_proto protoreflect.FileDescriptor

var file_cargo_v1_cargo_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11,
	0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52,
	0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x22, 0x34, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x67,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x22, 0x32, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64,
	0x22, 0x3d, 0x0a, 0x0f, 0x48, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x22, 0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xad, 0x02, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f,
	0x12, 0x15, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x7b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x5b, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x22, 0x0f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61,
	0x72, 0x67, 0x6f, 0x12, 0x5e, 0x0a, 0x0c, 0x48, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x22, 0x0f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x42, 0x8e, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x61, 0x72, 0x67,
	0x6f, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x68, 0x61, 0x6f, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x3b,
	0x63, 0x61, 0x72, 0x67, 0x6f, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x14, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x43, 0x61, 0x72, 0x67, 0x6f,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cargo_v1_cargo_proto_rawDescOnce sync.Once
	file_cargo_v1_cargo_proto_rawDescData = file_cargo_v1_cargo_proto_rawDesc
)

func file_cargo_v1_cargo_proto_rawDescGZIP() []byte {
	file_cargo_v1_cargo_proto_rawDescOnce.Do(func() {
		file_cargo_v1_cargo_proto_rawDescData = protoimpl.X.CompressGZIP(file_cargo_v1_cargo_proto_rawDescData)
	})
	return file_cargo_v1_cargo_proto_rawDescData
}

var file_cargo_v1_cargo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cargo_v1_cargo_proto_goTypes = []interface{}{
	(*GetCargoReq)(nil),         // 0: cargo.v1.GetCargoReq
	(*GetCargoResp)(nil),        // 1: cargo.v1.GetCargoResp
	(*CreateCargoReq)(nil),      // 2: cargo.v1.CreateCargoReq
	(*CreateCargoResp)(nil),     // 3: cargo.v1.CreateCargoResp
	(*HandingEventReq)(nil),     // 4: cargo.v1.HandingEventReq
	(*HandingEventResp)(nil),    // 5: cargo.v1.HandingEventResp
	(*cargo.Cargo)(nil),         // 6: cargo.Cargo
	(*cargo.HandlingEvent)(nil), // 7: cargo.HandlingEvent
}
var file_cargo_v1_cargo_proto_depIdxs = []int32{
	6, // 0: cargo.v1.GetCargoResp.cargo:type_name -> cargo.Cargo
	6, // 1: cargo.v1.CreateCargoReq.cargo:type_name -> cargo.Cargo
	7, // 2: cargo.v1.HandingEventReq.event:type_name -> cargo.HandlingEvent
	0, // 3: cargo.v1.CargoService.GetCargo:input_type -> cargo.v1.GetCargoReq
	2, // 4: cargo.v1.CargoService.CreateCargo:input_type -> cargo.v1.CreateCargoReq
	4, // 5: cargo.v1.CargoService.HandingEvent:input_type -> cargo.v1.HandingEventReq
	1, // 6: cargo.v1.CargoService.GetCargo:output_type -> cargo.v1.GetCargoResp
	3, // 7: cargo.v1.CargoService.CreateCargo:output_type -> cargo.v1.CreateCargoResp
	5, // 8: cargo.v1.CargoService.HandingEvent:output_type -> cargo.v1.HandingEventResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cargo_v1_cargo_proto_init() }
func file_cargo_v1_cargo_proto_init() {
	if File_cargo_v1_cargo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cargo_v1_cargo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCargoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_v1_cargo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCargoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_v1_cargo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCargoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_v1_cargo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCargoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_v1_cargo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandingEventReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargo_v1_cargo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandingEventResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cargo_v1_cargo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cargo_v1_cargo_proto_goTypes,
		DependencyIndexes: file_cargo_v1_cargo_proto_depIdxs,
		MessageInfos:      file_cargo_v1_cargo_proto_msgTypes,
	}.Build()
	File_cargo_v1_cargo_proto = out.File
	file_cargo_v1_cargo_proto_rawDesc = nil
	file_cargo_v1_cargo_proto_goTypes = nil
	file_cargo_v1_cargo_proto_depIdxs = nil
}
